version: '3'
services:
        fastapi:
                build: ./backend
                working_dir: /backend/app
                command: ["uvicorn", "main:app", "--reload"]
                volumes:
                        - ./backend:/app/backend
                ports:
                        - "8000:8000"
        frontend:
                build: ./frontend
                command: ["npm", "start"]
                volumes:
                        - ./frontend:/app/frontend
                ports:
                        - "3000:3000"
volumes:
        node-modules:
