version: '3'
services:
        fastapi:
                build: ./backend
                command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
                volumes:
                        - ./backend:/app/backend
                ports:
                        - "8000:8000"
        frontend:
                build: ./frontend
                command: ["npm", "start"]
                volumes:
                        - ./frontend:/app/frontend
                ports:
                        - "3000:3000"
        redis:
                image: redis
                volumes:
                        - redis-volume:/usr/local/etc/redis
                ports:
                        - "6379:6379"

volumes:
        node-modules:
        redis-volume:
