version: '3'
services:
        fastapi:
                build: ./backend
                command: ["uvicorn", "main:app", "--reload"]
                environment:
                        - OPEN_WEATHER_API_KEY : bd7fbd53339fa23cdc6fc863e601bd9e
                volumes:
                        - ./backend:/app/backend
                ports:
                        - "8000:8000"
        frontend:
                build: ./frontend
                command: ["npm", "start"]
                environment: 
                        PROXY_API: http://localhost:8000
                volumes:
                        - ./frontend:/app/frontend
                ports:
                        - "3000:3000"
volumes:
        node-modules:
