version: '3'
services:
        fastapi:
                build: ./backend
                command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
                volumes:
                        - ./backend:/app/backend

                environment:
                        - PYTHONUNBUFFERED = 1
                        - OPEN_WEATHER_API_KEY = "bd7fbd53339fa23cdc6fc863e601bd9e"
                        - DB_TYPE = "postgresql"
                        - DB_NAME = "postgres"
                        - DB_USER = "postgres"
                        - DB_PASSWORD = "password"
                        - DB_HOST = db
                        - DB_PORT = 5432
                        - MYSQL_DRIVER = "mysql driver"
                        - SQLALCHEMY_URL = postgresql://postgres:password@db/postgres
                ports:
                        - "8000:8000"
                links:
                        - redis
                        - db
                networks:
                        - internal-net
        db:
                image: postgres:12-alpine
                volumes:
                        - postgres_data:/var/lib/postgresql/data
                environment:
                        - POSTGRES_DB = "postgres"
                        - POSTGRES_USER = "postgres"
                        - POSTGRES_PASSWORD = "password"
                ports:
                        - "5432:5432"
                networks:
                        - internal-net
        frontend:
                build: ./frontend
                command: ["npm", "start"]
                volumes:
                        - ./frontend:/app/frontend
                ports:
                        - "3000:3000"
                networks:
                        - internal-net
        redis:
                image: redis
                volumes:
                        - redis-volume:/usr/local/etc/redis
                ports:
                        - "6379:6379"
                networks:
                        - internal-net

volumes:
        node-modules:
        redis-volume:
        postgres_data:
networks:
        internal-net:
